### ISSUE TITLE
Can you please add a tag to the latest version?

### ISSUE THREAD

**Issue by Rosi2143** [mintoko/fidl2adoc#11]
To refer to you project from other projects I would like to have a tag (specified version) of the project.

Can you please attach a tag e.g. v0.1 to 7b30d4a3b37db7eb06cbbfe3c37dd8da58ead050?

Thanks

**Comment by mintoko** [comment]
https://github.com/mintoko/fidl2adoc/releases/tag/v0.1

**Comment by Rosi2143** [comment]
Thanks.
